version: '2'
services:
    mysql:
      image: mariadb:latest
      volumes:
        - ./docker/mysql-data:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: database

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
      - mysql
      ports:
      - '8085:80'
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USERNAME: root
        PMA_HOST: mysql